export { default as HeroSection } from './HeroSection/HeroSection';
export { default as ServiceSection } from './ServiceSection/ServiceSection';
export { default as HowItWorkSection } from './HowItWorkSection/HowItWorkSection';
export { default as ContactSection } from './ContactSection/ContactSection';
export { default as HeadingSection } from './HeadingSection/HeadingSection';
export { default as HeadingSectionSecondary } from './HeadingSectionSecondary/HeadingSectionSecondary';
export { default as HorizontalCardSection } from './HorizontalCardSection/HorizontalCardSection';
export { default as IntegrationSection } from './IntegrationSection/IntegrationSection';
export { default as DescriptionListSection } from './DescriptionListSection/DescriptionListSection';
